export const CONTACT = {
  name: "Tony Anderson",
  title: "Regional Quality Manager | QA/QC Manager | Quality Assurance & Compliance Executive",
  email: "anderson.tony83@gmail.com",
  phone: "+33 685196452",
  address: "3 Rue Jacques Cartier, 34200 Sète, France",
  linkedin: "https://www.linkedin.com/in/tony-anderson-62719084/",
  resume: "/docs/Tony_Anderson_Resume.pdf",
  loi: "/docs/Tony_Anderson_LOI.pdf",
  sop: "/docs/Tony_Anderson_SOP.pdf",
};

export const NAV = [
  { to: "/", label: "Home" },
  { to: "/about", label: "About" },
  { to: "/experience", label: "Experience" },
  { to: "/projects", label: "Projects" },
  { to: "/expertise", label: "Expertise" },
  { to: "/certifications", label: "Certifications" },
  { to: "/insights", label: "Insights" },
  { to: "/resources", label: "Resources" },
  { to: "/contact", label: "Contact" },
] as const;

export const STATS = [
  { value: 20, suffix: "+", label: "Years of International Experience" },
  { value: 50, suffix: "+", label: "Major Infrastructure Projects" },
  { value: 12, suffix: "+", label: "Global Organizations Served" },
  { value: 10, suffix: "+", label: "Countries of Operation" },
  { value: 100, suffix: "%", label: "Commitment to Quality Excellence" },
];

export const CLIENTS = [
  "EDF", "BP", "Chevron", "INEOS", "Total", "Wood",
  "Bonatti", "Vinci Energies", "Framatome", "Lloyd's Register",
  "Transocean", "Vattenfall",
];

export const INDUSTRIES = [
  { name: "Oil & Gas", desc: "Upstream, midstream and downstream quality leadership across refineries, depots and pipelines." },
  { name: "Power Generation", desc: "Conventional and nuclear power infrastructure, including EDF and Hinkley Point C programs." },
  { name: "Petrochemical", desc: "Large-scale petrochemical construction and turnaround quality governance." },
  { name: "EPC", desc: "Multidisciplinary EPC project quality management from engineering to handover." },
  { name: "Offshore", desc: "Subsea equipment, drilling programs and offshore wind quality assurance." },
  { name: "Infrastructure", desc: "Industrial construction, civil works and heavy infrastructure quality frameworks." },
  { name: "Manufacturing", desc: "Fabrication surveillance, FAT witnessing and supplier quality management." },
  { name: "Energy", desc: "Renewables, offshore wind and integrated energy transition projects." },
  { name: "Industrial Construction", desc: "Site quality leadership across civil, mechanical, piping, E&I and coatings." },
];

export const EXPERTISE = [
  { title: "Quality Management Systems", cat: "Governance", desc: "Designing and implementing ISO 9001-aligned QMS frameworks that scale across multi-site programs." },
  { title: "Quality Assurance", cat: "Governance", desc: "Establishing preventive quality strategies, procedures and controls across the project lifecycle." },
  { title: "Quality Control", cat: "Execution", desc: "Directing inspection, testing and verification of construction and fabrication activities." },
  { title: "ISO 9001 Compliance", cat: "Compliance", desc: "Certification readiness, internal audits and continuous conformance across international operations." },
  { title: "Auditing", cat: "Compliance", desc: "Corporate, project, contractor and supplier auditing programs with structured CAPA management." },
  { title: "Supplier Quality Management", cat: "Supply Chain", desc: "Vendor qualification, surveillance, FAT witnessing and manufacturing quality oversight." },
  { title: "Contractor Management", cat: "Supply Chain", desc: "Contractor quality performance, deviation control and compliance assurance." },
  { title: "Risk Assessment", cat: "Governance", desc: "Structured quality risk identification, mitigation and monitoring across complex programs." },
  { title: "Regulatory Compliance", cat: "Compliance", desc: "DESP, PED, ASME, API and international regulatory frameworks across energy and industrial sectors." },
  { title: "Mechanical Completion", cat: "Execution", desc: "Systemization, punch-list management, walkdowns and readiness for commissioning." },
  { title: "Turnover Documentation", cat: "Execution", desc: "Final record books, MDRs, dossier assembly and client acceptance packages." },
  { title: "Inspection & Test Plans", cat: "Execution", desc: "Discipline-specific ITPs across civil, structural, mechanical, piping, HVAC, coating and E&I." },
  { title: "Welding Inspection", cat: "Technical", desc: "AWS CWI-led welding surveillance, WPS/PQR review and welder qualification management." },
  { title: "Non-Destructive Testing", cat: "Technical", desc: "RT, UT, MT, PT and VT program oversight rooted in ASNT Level II background." },
  { title: "Pressure Equipment Compliance", cat: "Compliance", desc: "DESP / PED, API 510 / 570 / 653 conformance for fixed equipment and piping." },
  { title: "Construction Quality Oversight", cat: "Execution", desc: "Site quality leadership from mobilization through mechanical completion and handover." },
  { title: "NCR & CAPA Management", cat: "Governance", desc: "Non-conformance workflows, root cause analysis and corrective/preventive action closure." },
  { title: "KPI Reporting & Analytics", cat: "Governance", desc: "Quality performance dashboards for executive, client and stakeholder reporting." },
];

export const EXPERIENCE = [
  {
    role: "QA/QC Manager",
    company: "EDF Power Generation Project — Bonatti Spa",
    location: "France",
    period: "Nov 2025 — Present",
    summary: "Leading project quality management on a strategic EDF power generation infrastructure program.",
    bullets: [
      "Lead a multidisciplinary team of 10 quality inspectors across civil, structural, mechanical, piping, HVAC, coating and E&I.",
      "Develop and deploy project-specific ITPs, quality procedures and compliance frameworks tailored to EDF standards.",
      "Direct NCR management, corrective actions, contractor compliance and quality performance monitoring.",
      "Interface with EDF, APAVE, subcontractors and stakeholders to align quality expectations across the program.",
      "Own project KPIs covering inspections, audits, mechanical completion and turnover activities.",
    ],
    tags: ["Power Generation", "EPC", "Team Leadership", "EDF"],
  },
  {
    role: "Owner & Principal Quality Consultant",
    company: "Integrity Inspections EUR",
    location: "France",
    period: "Sep 2014 — Mar 2026",
    summary: "Founder-led independent QA/QC consultancy serving global energy and industrial clients.",
    bullets: [
      "Delivered supplier surveillance, welding inspection, construction quality oversight and audit programs across Europe.",
      "Served major clients including EDF, INEOS, BP, Chevron, Total and Wood Group.",
      "Built quality procedures, inspection programs and NCR frameworks tailored to each client's compliance posture.",
      "Represented clients on vendor assessments, quality audits and project quality assurance activities.",
    ],
    tags: ["Consulting", "Supplier Quality", "Auditing"],
  },
  {
    role: "QA/QC Manager",
    company: "INEOS Project One",
    location: "Belgium",
    period: "Sep 2024 — Jul 2025",
    summary: "Quality leadership on one of Europe's largest petrochemical infrastructure programs.",
    bullets: [
      "Directed QA/QC across civil, structural, mechanical, piping, HVAC, coating and E&I scopes.",
      "Managed client inspections, RFIs, NCR closure and quality documentation processes.",
      "Coordinated multidisciplinary inspection teams and supported mechanical completion milestones.",
    ],
    tags: ["Petrochemical", "EPC", "Mechanical Completion"],
  },
  {
    role: "QA/QC Supervisor",
    company: "BP Petroleum Depot",
    location: "France",
    period: "Jan 2022 — Jul 2024",
    summary: "Quality oversight of a major petroleum storage infrastructure refurbishment.",
    bullets: [
      "Managed contractor quality performance, NCRs, concession requests and final acceptance activities.",
      "Directed welding, coating, civil and structural inspections against international standards.",
      "Supported refurbishment of large-capacity tanks including shells, floors, floating roofs, piping and systems.",
    ],
    tags: ["Oil & Gas", "Inspection", "BP"],
  },
  {
    role: "Assistant QC Manager / Senior Quality Consultant",
    company: "Chevron Anchor & Ballymore — Lloyd's Register",
    location: "International",
    period: "Dec 2020 — Apr 2022",
    summary: "Manufacturing surveillance of 20K subsea drilling equipment for deepwater Gulf of Mexico projects.",
    bullets: [
      "Performed welding audits, NDT audits, FAT witnessing and quality documentation reviews.",
      "Supported fabrication and testing of 20K FLS Gate Valves, Flowspools, Tees, Elbows and Crossovers.",
      "Identified quality concerns and coordinated corrective actions with manufacturing stakeholders.",
    ],
    tags: ["Offshore", "Subsea", "Chevron", "Lloyd's Register"],
  },
  {
    role: "Quality Consultant — Total Donges Refinery",
    company: "IREM France",
    location: "France",
    period: "Sep 2021 — Dec 2021",
    summary: "Welding and NDT program development for a major refinery upgrade.",
    bullets: [
      "Developed and revised project-specific welding, NDT and PWHT procedures.",
      "Managed welder qualification matrices and qualification records.",
      "Witnessed and validated welding qualification testing programs.",
    ],
    tags: ["Refinery", "Welding", "Total"],
  },
  {
    role: "QA/QC Manager",
    company: "Vinci Energies — BP VGAP Project",
    location: "France",
    period: "Oct 2019 — Dec 2020",
    summary: "Multidiscipline quality management across piping, instrumentation, electrical, civil, coating and welding.",
    bullets: [
      "Managed DESP certification requirements and regulatory compliance processes.",
      "Directed NCR management, turnover dossiers and client acceptance activities.",
      "Owned project quality documentation from engineering through handover.",
    ],
    tags: ["Oil & Gas", "DESP", "Vinci Energies"],
  },
  {
    role: "QA/QC Manager",
    company: "Wood Group — Borealis Project",
    location: "France",
    period: "Mar 2018 — Jul 2018",
    summary: "Project quality management for a petrochemical program.",
    bullets: [
      "Implemented and maintained project QMS procedures.",
      "Approved quality plans, inspection plans and contractor documentation.",
      "Coordinated audits, quality inspections and turnover documentation.",
    ],
    tags: ["Petrochemical", "Wood", "Borealis"],
  },
  {
    role: "QA/QC Coordinator & Inspector",
    company: "Huisman Equipment",
    location: "Netherlands",
    period: "Mar 2017 — Mar 2018",
    summary: "Fabrication quality oversight for offshore crane construction.",
    bullets: [
      "Coordinated client and classification society inspections.",
      "Supervised welding, NDT, coating and structural steel quality activities.",
    ],
    tags: ["Offshore", "Fabrication"],
  },
  {
    role: "Lead Inspector & Resident Surveyor",
    company: "Transocean Deepwater Drilling",
    location: "France",
    period: "Nov 2012 — Jan 2017",
    summary: "Client representative for manufacturing, testing and delivery of offshore drilling equipment.",
    bullets: [
      "Managed vendor surveillance, production monitoring and compliance verification.",
      "Reviewed data books and coordinated FAT programs and quality acceptance.",
      "Supported delivery of critical subsea and drilling equipment programs.",
    ],
    tags: ["Offshore", "Transocean", "Surveillance"],
  },
  {
    role: "QC Supervisor",
    company: "IESCO — Flint Hills Resources Refinery",
    location: "Rosemount, Minnesota, USA",
    period: "Oct 2011 — Jul 2012",
    summary: "Refinery piping fabrication and installation quality supervision at one of the largest US refineries.",
    bullets: [
      "Supervised piping fabrication, welding, testing and installation activities.",
      "Oversaw welder qualification testing and production welding.",
      "Witnessed hydrostatic, pneumatic, static and service testing of piping systems.",
      "Reviewed PMI and PWHT results and verified code compliance.",
    ],
    tags: ["Refinery", "Piping", "USA"],
  },
];

export const PROJECTS = [
  {
    slug: "edf-power-generation",
    client: "EDF",
    name: "EDF Power Generation Program",
    industry: "Power Generation",
    year: "2025 — Present",
    challenge: "Deliver rigorous quality governance across a strategic power generation infrastructure build with multi-discipline scope and stringent EDF standards.",
    strategy: "Established discipline-specific ITPs, contractor compliance frameworks and executive KPI reporting aligned to EDF and APAVE expectations.",
    execution: "Leading a 10-strong inspection team spanning civil, structural, mechanical, piping, HVAC, coating and E&I with structured NCR and CAPA workflows.",
    outcome: "Predictable quality performance, transparent stakeholder alignment and disciplined progress toward mechanical completion.",
  },
  {
    slug: "ineos-project-one",
    client: "INEOS",
    name: "INEOS Project One",
    industry: "Petrochemical",
    year: "2024 — 2025",
    challenge: "Manage QA/QC on one of Europe's largest petrochemical infrastructure investments with tight completion milestones.",
    strategy: "Built integrated inspection programs across all disciplines and standardized client inspection and RFI workflows.",
    execution: "Directed multidisciplinary inspection teams, NCR closure processes and mechanical completion readiness.",
    outcome: "Consistent quality assurance and closure velocity supporting the program's mechanical completion trajectory.",
  },
  {
    slug: "bp-petroleum-infrastructure",
    client: "BP",
    name: "BP Petroleum Infrastructure — Depot Refurbishment",
    industry: "Oil & Gas",
    year: "2022 — 2024",
    challenge: "Ensure regulatory-grade quality during large-scale refurbishment of high-capacity petroleum storage assets.",
    strategy: "Deployed disciplined inspection regimes across welding, coating, civil and structural scopes to align with API and BP standards.",
    execution: "Managed contractor quality, NCRs, concessions and final acceptance across shells, floors, floating roofs and piping systems.",
    outcome: "Successful refurbishment of multiple large-capacity tanks with structured deviation control and clean handover.",
  },
  {
    slug: "chevron-anchor-ballymore",
    client: "Chevron",
    name: "Chevron Anchor & Ballymore",
    industry: "Offshore Subsea",
    year: "2020 — 2022",
    challenge: "Assure manufacturing quality on 20K subsea equipment for deepwater Gulf of Mexico developments.",
    strategy: "Applied Lloyd's Register-led surveillance model across welding, NDT and FAT programs for critical subsea components.",
    execution: "Witnessed and audited fabrication of 20K FLS Gate Valves, Flowspools, Tees, Elbows and Crossovers.",
    outcome: "Early detection of manufacturing risks and coordinated corrective actions safeguarding delivery to Chevron.",
  },
  {
    slug: "total-donges-refinery",
    client: "TotalEnergies",
    name: "Total Donges Refinery",
    industry: "Refinery",
    year: "2021",
    challenge: "Refresh welding, NDT and PWHT programs to align with refinery upgrade requirements.",
    strategy: "Developed procedure suite, welder qualification matrices and testing protocols aligned to project codes.",
    execution: "Witnessed welding qualification testing and validated qualification records across trades.",
    outcome: "Robust welding foundation supporting reliable execution across the upgrade scope.",
  },
  {
    slug: "hinkley-point-c",
    client: "EDF Energy",
    name: "Hinkley Point C Nuclear Project",
    industry: "Nuclear Power",
    year: "Program",
    challenge: "Support quality oversight on the UK's flagship nuclear new-build program with the highest regulatory bar.",
    strategy: "Applied nuclear-grade quality frameworks, welding surveillance and supplier assurance methods.",
    execution: "Contributed to inspection, audit and technical quality activities aligned to nuclear codes and client expectations.",
    outcome: "Reinforced conformance and traceability across critical work packages.",
  },
  {
    slug: "borealis-petrochemical",
    client: "Borealis / Wood Group",
    name: "Borealis Petrochemical Program",
    industry: "Petrochemical",
    year: "2018",
    challenge: "Deploy consistent project quality management across a complex petrochemical build.",
    strategy: "Implemented QMS procedures, quality and inspection plans, and contractor quality documentation controls.",
    execution: "Coordinated audits, inspections and turnover documentation across the project lifecycle.",
    outcome: "Stable, auditable quality program supporting successful project delivery.",
  },
  {
    slug: "vattenfall-offshore-wind",
    client: "Vattenfall",
    name: "Vattenfall Offshore Wind Farm",
    industry: "Renewable Energy",
    year: "Program",
    challenge: "Assure quality on offshore wind infrastructure with challenging marine execution conditions.",
    strategy: "Applied structured surveillance and inspection frameworks aligned to offshore fabrication standards.",
    execution: "Contributed to fabrication and installation quality assurance across the offshore wind scope.",
    outcome: "Reliable quality outcomes supporting renewable energy delivery milestones.",
  },
  {
    slug: "transocean-deepwater",
    client: "Transocean",
    name: "Transocean Deepwater Drilling Programs",
    industry: "Offshore Drilling",
    year: "2012 — 2017",
    challenge: "Represent Transocean as resident client surveyor for manufacturing and delivery of critical drilling equipment.",
    strategy: "Owned vendor surveillance, production monitoring, compliance verification and FAT programs end-to-end.",
    execution: "Managed data book reviews and quality acceptance for subsea and drilling equipment programs.",
    outcome: "Consistent delivery of high-integrity equipment to Transocean fleet operations.",
  },
  {
    slug: "flint-hills-refinery",
    client: "Flint Hills Resources",
    name: "Flint Hills Resources Refinery — Rosemount",
    industry: "Refinery",
    year: "2011 — 2012",
    challenge: "Supervise piping fabrication, welding and installation quality at one of the largest US refineries.",
    strategy: "Applied ASME B31.3 and refinery-specific quality controls across contractor welding and installation activities.",
    execution: "Witnessed hydrostatic, pneumatic and service testing; reviewed PMI, PWHT and code compliance.",
    outcome: "Verified code-compliant piping delivery within active refinery operations.",
  },
  {
    slug: "bp-vgap",
    client: "BP / Vinci Energies",
    name: "BP VGAP Infrastructure Project",
    industry: "Oil & Gas",
    year: "2019 — 2020",
    challenge: "Deliver multidiscipline QA/QC leadership across piping, instrumentation, electrical, civil, coating and welding.",
    strategy: "Structured DESP certification, NCR management and turnover dossier workflows.",
    execution: "Directed quality documentation from engineering through client acceptance.",
    outcome: "Clean regulatory posture and successful project handover.",
  },
];

export const CERTIFICATIONS = [
  {
    name: "AWS Certified Welding Inspector (CWI)",
    body: "American Welding Society",
    status: "Active — Expires 2028",
    file: "/docs/AWS_CWI_Certification.pdf",
    desc: "Internationally recognized welding inspection credential covering visual inspection, WPS/PQR review, welder qualification and code compliance.",
  },
  {
    name: "API Certified Source Inspector — Fixed Equipment",
    body: "American Petroleum Institute",
    status: "Active — Expires 2027",
    file: "/docs/API_SI_Certification.pdf",
    desc: "Specialized inspection credential for fixed equipment fabrication and vendor surveillance in the oil & gas industry.",
  },
  {
    name: "OSHA 10",
    body: "Occupational Safety and Health Administration",
    status: "Certified",
    desc: "Foundational construction industry safety training aligned with OSHA standards.",
  },
  {
    name: "GIES 2 — Industrial Site Safety",
    body: "GIES",
    status: "Certified",
    desc: "European industrial site safety certification required for major EPC and industrial construction environments.",
  },
  {
    name: "Former ASNT NDT Level II — RT, UT, MT, PT, VT",
    body: "American Society for Nondestructive Testing",
    status: "Held 2004 — 2012 · Extensive practical NDT background",
    desc: "Multi-method NDT Level II credential underpinning years of hands-on inspection experience across industrial environments.",
  },
];

export const INSIGHTS = [
  { cat: "Leadership", title: "Quality as a Strategic Business Enabler", excerpt: "Why the strongest quality organizations run as risk-reduction and value-creation engines, not compliance departments." },
  { cat: "Operational Excellence", title: "From ITPs to Executive KPIs", excerpt: "Translating discipline-level inspection data into decision-grade metrics for executives and clients." },
  { cat: "Quality Culture", title: "Building a Contractor Quality Culture on Multi-Billion Programs", excerpt: "The behaviors, contracts and rituals that drive contractor accountability at scale." },
  { cat: "Compliance", title: "DESP, PED and the Reality of European Pressure Equipment Compliance", excerpt: "Practical lessons from delivering compliant pressure equipment programs across EPC environments." },
  { cat: "Risk Management", title: "Managing Quality Risk in EPC Programs", excerpt: "A structured approach to identifying, prioritizing and closing quality risk across the project lifecycle." },
  { cat: "Continuous Improvement", title: "The Discipline of Corrective Action That Actually Sticks", excerpt: "Why most CAPA programs fail — and the operating rhythm that makes root cause analysis reliable." },
  { cat: "Business Improvement", title: "Turnover Excellence: The Last Mile of Quality", excerpt: "Building final record books and MDRs that clients accept the first time." },
  { cat: "Speaking & Media", title: "Future Publications, Interviews & Podcasts", excerpt: "Selected topics available for keynote, panel and long-form conversation." },
];
